### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by balasankarc** [robdimarco/omniauth_crowd#26]
This is the output I get when I run `bundle install` and `bundle exec rake`. Can you help fix them?

```
$ bundle install

Resolving dependencies...
Using rake 10.3.2
Using i18n 0.6.11
Using json 1.8.1
Using minitest 5.4.0
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.1.4
Using addressable 2.3.6
Using bundler 1.10.6
Using safe_yaml 1.0.3
Using crack 0.4.2
Using diff-lcs 1.2.5
Using hashie 3.2.0
Using mini_portile 0.6.0
Using nokogiri 1.6.3.1
Using rack 1.5.2
Using omniauth 1.2.2
Using omniauth_crowd 2.2.3 from source at .
Using rack-test 0.6.2
Using rspec-support 3.0.3
Using rspec-core 3.0.3
Using rspec-expectations 3.0.3
Using rspec-mocks 3.0.3
Using rspec 3.0.0
Using webmock 1.18.0
Bundle complete! 7 Gemfile dependencies, 25 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

$ bundle exec rake

/usr/bin/ruby2.2 -I/var/lib/gems/2.2.0/gems/rspec-core-3.0.3/lib:/var/lib/gems/2.2.0/gems/rspec-support-3.0.3/lib -S /var/lib/gems/2.2.0/gems/rspec-core-3.0.3/exe/rspec ./spec/omniauth/strategies/crowd_spec.rb
/var/lib/gems/2.2.0/gems/safe_yaml-1.0.3/lib/safe_yaml/load.rb:43:in `<module:SafeYAML>': undefined method `tagged_classes' for Psych:Module (NoMethodError)
	from /var/lib/gems/2.2.0/gems/safe_yaml-1.0.3/lib/safe_yaml/load.rb:26:in `<top (required)>'
	from /var/lib/gems/2.2.0/gems/crack-0.4.2/lib/crack/json.rb:6:in `require'
	from /var/lib/gems/2.2.0/gems/crack-0.4.2/lib/crack/json.rb:6:in `<top (required)>'
	from /var/lib/gems/2.2.0/gems/crack-0.4.2/lib/crack.rb:6:in `require'
	from /var/lib/gems/2.2.0/gems/crack-0.4.2/lib/crack.rb:6:in `<top (required)>'
	from /var/lib/gems/2.2.0/gems/webmock-1.18.0/lib/webmock.rb:5:in `require'
	from /var/lib/gems/2.2.0/gems/webmock-1.18.0/lib/webmock.rb:5:in `<top (required)>'
	from /home/balasankarc/packaging/trying/omniauth-crowd/source/omniauth_crowd/spec/spec_helper.rb:4:in `require'
	from /home/balasankarc/packaging/trying/omniauth-crowd/source/omniauth_crowd/spec/spec_helper.rb:4:in `<top (required)>'
	from /home/balasankarc/packaging/trying/omniauth-crowd/source/omniauth_crowd/spec/omniauth/strategies/crowd_spec.rb:1:in `require'
	from /home/balasankarc/packaging/trying/omniauth-crowd/source/omniauth_crowd/spec/omniauth/strategies/crowd_spec.rb:1:in `<top (required)>'
	from /var/lib/gems/2.2.0/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in `load'
	from /var/lib/gems/2.2.0/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in `block in load_spec_files'
	from /var/lib/gems/2.2.0/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in `each'
	from /var/lib/gems/2.2.0/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in `load_spec_files'
	from /var/lib/gems/2.2.0/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:97:in `setup'
	from /var/lib/gems/2.2.0/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:85:in `run'
	from /var/lib/gems/2.2.0/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:70:in `run'
	from /var/lib/gems/2.2.0/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:38:in `invoke'
	from /var/lib/gems/2.2.0/gems/rspec-core-3.0.3/exe/rspec:4:in `<main>'
/usr/bin/ruby2.2 -I/var/lib/gems/2.2.0/gems/rspec-core-3.0.3/lib:/var/lib/gems/2.2.0/gems/rspec-support-3.0.3/lib -S /var/lib/gems/2.2.0/gems/rspec-core-3.0.3/exe/rspec ./spec/omniauth/strategies/crowd_spec.rb failed

```

**Comment by robdimarco** [comment]
Thanks for the issue. I upgraded the gems and all seems to be running now.
